### ISSUE TITLE
Does `qc` and `q` treat escaping backslash differently intentionally?

### ISSUE THREAD

**Issue by Wizek** [audreyt/interpolatedstring-perl6#4]
```
*Debug.Dump> putStrLn [qc|\"|]
"
*Debug.Dump> putStrLn [q|\"|]
\"
```

Is this intentional?

**Comment by audreyt** [comment]
Yes, that's how `qc` handles `\{` sequences.

**Comment by Wizek** [comment]
I am not sure I follow. I think it is okay of `{` and `\{` are given special meaning, but wouldn't it be possible to have the same behaviour for `\"` for the two?

**Comment by audreyt** [comment]
I see. You're completely right. :rainbow: Duly fixed as suggested.

**Comment by Wizek** [comment]
Thanks!
