### ISSUE TITLE
Does not build/configure in sandbox and ghc 7.10.3

### ISSUE THREAD

**Issue by testexplode** [audreyt/interpolatedstring-perl6#5]
Sorry, that I cannot give a better error message: 

in a clean sandbox 
(mkdir sandbox
cd sandbox
cabal sandbox init
cabal install interpolatedstring-perl6

gives
....
registering haskell-src-meta-0.6.0.13...
Installed haskell-src-meta-0.6.0.13
[1 of 1] Compiling Main             ( /tmp/cabal-tmp-25225/interpolatedstring-perl6-1.0.0/dist/dist-sandbox-ce47e07d/setup/setup.hs, /tmp/cabal-tmp-25225/interpolatedstring-perl6-1.0.0/dist/dist-sandbox-ce47e07d/setup/Main.o )

/tmp/cabal-tmp-25225/interpolatedstring-perl6-1.0.0/dist/dist-sandbox-ce47e07d/setup/setup.hs:4:49: Warning:
    In the use of ‘runTests’
    (imported from Distribution.Simple, but defined in Distribution.Simple.UserHooks):
    Deprecated: "Please use the new testing interface instead!"
Linking /tmp/cabal-tmp-25225/interpolatedstring-perl6-1.0.0/dist/dist-sandbox-ce47e07d/setup/setup ...
Configuring interpolatedstring-perl6-1.0.0...
Failed to install interpolatedstring-perl6-1.0.0
Updating documentation index
/home/user/programming/haskell/sandbox2/.cabal-sandbox/share/doc/x86_64-linux-ghc-7.10.3/index.html
cabal: Error: some packages failed to install:
interpolatedstring-perl6-1.0.0 failed during the configure step. The exception
was:
ExitFailure (-11)

[user@computer ~/programming/haskell/sandbox2]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3

**Comment by audreyt** [comment]
Hi, I just tried with GHC 8.0.1 (Haskell Platform, Windows) and it seems to install fine — the initial attempt failed but re-running seems to work.

On OSX I tried both GHC 7.10.2 and GHC 7.10.3 and they both worked on the first try. I haven't tried Linux, though, so maybe it's something specific to Linux?

In any case please try again with the new GHC 8.0.1 and see if it helps; or try `cabal install -v3 interpolatedstring-perl6` to obtain a more verbose log.
